### ISSUE TITLE
Meson configure fails without appstream-utils

### ISSUE THREAD

**Issue by Cogitri** [Cogitri/gxi#78]
```
=> gxi-0.5.0_1: running do_configure ...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 112, in run
    return options.run_func(options)
  File "/usr/lib/python3.6/site-packages/mesonbuild/msetup.py", line 230, in run
    app.generate()
  File "/usr/lib/python3.6/site-packages/mesonbuild/msetup.py", line 161, in generate
    self._generate(env)
  File "/usr/lib/python3.6/site-packages/mesonbuild/msetup.py", line 190, in _generate
    intr.run()
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 3874, in run
    super().run()
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 408, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 432, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 426, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 437, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 763, in function_call
    return func(node, posargs, kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 292, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 181, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 3447, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 432, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 426, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 439, in evaluate_statement
    return self.assignment(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 1019, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 437, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 763, in function_call
    return func(node, posargs, kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 292, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 181, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2194, in func_run_command
    return self.run_command_impl(node, args, kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2238, in run_command_impl
    if not cmd_path.startswith('..') and cmd_path not in self.build_def_files:
AttributeError: 'NoneType' object has no attribute 'startswith'
The Meson build system
Version: 0.49.2
Source dir: /builddir/gxi-0.5.0
Build dir: /builddir/gxi-0.5.0/build
Build type: native build
Project name: gxi
Project version: 0.5.0
Appending LDFLAGS from environment: '-Wl,-z,relro -Wl,-z,now -Wl,--as-needed    '
Native Rust compiler: rustc (rustc 1.32.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Dependency glib-2.0 found: YES 2.58.3
Dependency gio-2.0 found: YES 2.58.3
Dependency cairo found: YES 1.16.0
Dependency pango found: YES 1.42.4
Dependency gtk+-3.0 found: YES 3.24.5
Program desktop-file-validate found: NO
Program appstream-util found: NO
```

**Comment by Cogitri** [comment]
Fixed by b2b25f7d
